on:
  push:
    branches:
      - changed-files-test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: changedDirs
        uses: tj-actions/changed-files@v29.0.7
        with:
          dir_names: true
          files: ./producers/**
      - name: print it uwu
        run: |
          echo $(
            for dir in ${{ steps.changedDirs.outputs.all_modified_files }}
            do
                echo $dir | sed -n 's|^producers/\([^/]*\).*$|\1|p' # extract producer name from directory path
            done # (below) remove duplicate entries
          ) | tr " " "\n" \
            | sort \
            | uniq \
            | tr "\n" " "
