on:
  workflow_call:
    inputs:
      input1:
        type: string
        required: true

jobs:
  runTest:
    name: run test
    runs-on: ubuntu-latest
    steps:
      - name: print one
        shell: bash
        run: echo "${{ inputs.input1 }}"
