on:
  workflow_call:
    secrets:
      secret1:
        type: string
        required: true
    inputs:
      input1:
        type: string
        required: true

jobs:
  runTest:
    name: run test
    runs-on: ubuntu-latest
    steps:
      - name: print input
        shell: bash
        run: echo "${{ inputs.input1 }}"
      - name: print secret
        shell: bash
        run: echo "${{ secrets.secret1 }}"
