on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  runTest:
    name: run test
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: print input
        shell: bash
        run: echo "${{ inputs.input1 }}"
      - name: print secret
        shell: bash
        run: echo "${{ secrets.secret1 }}"
