on:
  push:
    branches:
      - changed-files-test

jobs:
  getChangedProducers:
    runs-on: ubuntu-latest
    outputs:
      changedDirs: steps.processed.outputs.changedDirs
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: changedDirs
        uses: tj-actions/changed-files@v29.0.7
        with:
          dir_names: true
          files: ./producers/**
      - id: processed
        run: |
          changedDirs=[$(
                echo $(
                  for dir in producers/p1 producers/p2 producers/p2/subdir producers/p3 producers/p4 producers/p5
                  do
                      echo $dir | sed -n 's|^producers/\([^/]*\).*$|\1|p' # extract producer name from directory path
                  done
              ) | tr " " "\n" \
                | sort \
                | uniq \
                | while read -r line; do
                      echo \"$line\",
                  done \
                | tr "\n" " " \
                | rev | cut -c 3- | rev
          )]
          echo $changedDirs
          echo ::set-output name=changedDirs::$changedDirs

  printProducers:
    runs-on: ubuntu-latest
    needs: [getChangedProducers]
    strategy:
      matrix: 
        producer: ${{ fromJSON(needs.getChangedProducers.outputs.changedDirs) }}
    steps:
      - run: echo ${{ matrix.producer }}
