on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  runTest:
    name: run test
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: print one
        shell: bash
        run: echo ${{secrets.INPUT1}} | sed 's/./& /g'
