on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      input1:
        type: string
        required: true

jobs:
  runTest1:
    name: run test out of env
    runs-on: ubuntu-latest
    steps:
      - name: print one
        shell: bash
        run: echo ${{inputs.INPUT1}} | sed 's/./& /g'

  runTest2:
    name: run test in env
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: print one
        shell: bash
        run: echo ${{secrets.INPUT1}} | sed 's/./& /g'
