on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  runTest:
    name: run test
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      INPUT1: ${{ secrets.INPUT1 }}
      SECRET1: ${{ secrets.SECRET1 }}
    steps:
      - name: print env
        shell: bash
        run: echo "${{ inputs.environment }}"
      - name: print input
        shell: bash
        run: echo "${{ env.INPUT1 }}"
      - name: print secret
        shell: bash
        run: echo "${{ env.SECRET1 }}"
