on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      val:
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: test-call
      - uses: melendezd/action-test/.github/workflows/called2.yml@test-call
        with: 
          val: inputs.val
