on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      val:
        required: true
        type: string

jobs:
  job1:
    uses: ${{ inputs.path }}
    with: 
      val: inputs.val
