on: 
  push:
    branches:
      - main
        
jobs:
  call-the-workflow:
    environment: prod
    uses: ./.github/workflows/base.yml
    with:
      input1: ${{ secrets.input1 }}
    secrets:
      input1: ${{ secrets.secret1 }}
