on: 
  push:
    branches:
      - main
        
jobs:
  call-the-workflow:
    environment: prod
    steps:
      - uses: ./.github/workflows/base.yml
        with:
          input1: ${{ secrets.input1 }}
        secrets:
          input1: ${{ secrets.secret1 }}
