on: 
  push:
    branches:
      - main 

jobs:
  call-the-workflow:
    uses: ./.github/workflows/base.yml
    with: 
      environment: prod
      input1: asfd
    secrets: inherit

  call-the-workflow-2:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/base.yml
        with: 
          environment: prod
          input1: ${{ secrets.INPUT1 }}
