on: 
  push:
    branches:
      - approve
        
jobs:
  job1:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - shell: bash
        run: |
          echo "::warning title=woah there::hold up 1"
  job2:
    runs-on: ubuntu-latest
    environment: approve
    needs: job1
    steps:
      - shell: bash
        run: |
          echo "::warning title=woah there::hold up 2"
  job3:
    runs-on: ubuntu-latest
    environment: dev
    needs: job2
    if: ${{ always() && needs.job2.result == 'success' }}
    steps:
      - shell: bash
        run: |
          echo "done!"
