on: 
  push:
    branches:
      - main
        
jobs:
  call-workflow:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: ./.github/workflows/base.yml
        secrets:
          input1: ${{ secrets.secret1 }}
