on: 
  push:
    branches:
      - main
        
jobs:
  call-the-workflow:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v1
      - shell: bash
        run: ls
      - uses: ./.github/workflows/base.yml
        with:
          input1: ${{ secrets.input1 }}
          secret1: ${{ secrets.secret1 }}
