on: 
  push:
    branches:
      - approve
        
jobs:
  job1:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      val: bye
    steps:
      - shell: bash
        run: |
          echo "::warning title=woah there::hold up 1"
  job2:
    runs-on: ubuntu-latest
    environment: approve
    needs: job1
    steps:
      - shell: bash
        run: ''
  job3:
    runs-on: ubuntu-latest
    environment: dev
    needs: [job1, job2]
    if: ${{ always() && (needs.job2.result == 'success' || needs.job1.outputs.val == 'hi') }}
    steps:
      - shell: bash
        run: |
          echo "done!"
