on: 
  push:
    branches:
      - dev
        
jobs:
  call-workflow:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: ./.github/workflows/base.yml
        with:
          input1: ${{ secrets.input1 }}
        secrets:
          input1: ${{ secrets.secret1 }}
