on: 
  push:
    branches:
      - main
        
jobs:
  call-the-workflow:
    runs-on: ubuntu-latest
    uses: melendezd/action-test/.github/workflows/base.yml@main
    with: 
      environment: prod
